apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: event-service
  template:
    metadata:
      labels:
        app: event-service
    spec:
      containers:
      - name: event-service
        image: felipegoes7/event-service:v3
        ports:
        - containerPort: 5000
        env:
        - name: DB_NAME
          value: event_db
        - name: DB_USER
          value: admin
        - name: DB_PASSWORD
          value: admin123
        - name: DB_HOST
          value: postgres-events
        - name: DB_PORT
          value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: event-service
spec:
  selector:
    app: event-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
