apiVersion: apps/v1
kind: Deployment
metadata:
  name: interface
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interface
  template:
    metadata:
      labels:
        app: interface
    spec:
      containers:
      - name: interface
        image: felipegoes7/interface-service:latest
        ports:
        - containerPort: 5010
        stdin: true  # Habilitar a entrada padrão
        tty: true    # Habilitar o terminal (tty)
---
apiVersion: v1
kind: Service
metadata:
  name: interface-service
spec:
  selector:
    app: interface-service
  ports:
    - protocol: TCP
      port: 5010
      targetPort: 5010
  type: LoadBalancer