apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: felipegoes7/order-service:v3
        ports:
        - containerPort: 5004
        env:
        - name: DB_NAME
          value: order_db
        - name: DB_USER
          value: admin
        - name: DB_PASSWORD
          value: admin123
        - name: DB_HOST
          value: postgres-orders
        - name: DB_PORT
          value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 5004
      targetPort: 5004
  type: LoadBalancer
