apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: felipegoes7/payment-service:v1
        ports:
        - containerPort: 5001
        env:
        - name: DB_NAME
          value: payment_db
        - name: DB_USER
          value: admin
        - name: DB_PASSWORD
          value: admin123
        - name: DB_HOST
          value: postgres-payments
        - name: DB_PORT
          value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: LoadBalancer
